### ISSUE TITLE
Access network_node using DockerClient and DockerUtil::network

### ISSUE THREAD

**Issue by iarp** [llalon/unraid-plugin-composerize#6]
include/Composerize.php:

```php
<?php

$docroot = $docroot ?? $_SERVER['DOCUMENT_ROOT'] ?: '/usr/local/emhttp';

require_once("$docroot/plugins/composerize/include/Definitions.php");
require_once("$docroot/plugins/composerize/include/Util.php");
require_once("$docroot/plugins/dynamix.docker.manager/include/DockerClient.php");

$custom = DockerUtil::custom();
$subnet = DockerUtil::network($custom);

require_once("$docroot/plugins/dynamix.docker.manager/include/Helpers.php"); // From dynamic docker plugin
```

That will allow the network_mode to be set to the network setting in unraids docker ui. However it's not wrapped in quotes nor is there an entry a the bottom declaring the network. That seems to be an issue with composerize itself though, their own websites utility spits out the same unquoted string and no network defined.

Edit: Also just noticed it brings up the ports assignments.

**Comment by llalon** [comment]
Yes this is an issue with composerize. Future direction is to reimplement it in php specific to unraid.

**Comment by iarp** [comment]
Well. I'll agree that composerize is the issue when it comes to the final output not having quotes and the network entry not being declared. 

It is an issue that this plugins Composerize.php file is missing those lines as without them you don't get network or ports of any fashion.

**Comment by llalon** [comment]
updated in v1.1
