### ISSUE TITLE
no this plugin in Unraid anymore ?

### ISSUE THREAD

**Issue by masterwishx** [llalon/unraid-plugin-composerize#9]
cant find this plugin in CA apps in Unraid
is it depricated?

**Comment by thejasonparker** [comment]
You can install it using this url using  Plugins > Install Plugin https://raw.githubusercontent.com/llalon/unraid-plugin-composerize/main/plugin/composerize.plg

**Comment by llalon** [comment]
Not deprecated. It was never added to CA app repo.
